accounts/urls.py
# accounts/urls.py
from django.urls import path
from .views import signup, log_in_view, log_out_view, profile

urlpatterns = [
    path('signup/', signup, name='signup'),
    path('login/', log_in_view, name='login'),
    path('logout/', log_out_view, name='logout'),
    path('profile/', profile, name='profile'),
]

myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from myshop import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('orders/', include('orders.urls')),
    path('', include('store.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)

store/urls.py
# store/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from .views import all_products, category_detail, subcategory_detail, cart_view, add_to_cart, update_cart, remove_from_cart, search_products

urlpatterns = [

    # основные
    path('', views.home, name='home'),
    path('products/', all_products, name='all-products'),
    path('product/<int:product_id>/', views.product_detail, name='product_detail'),

    # Просмотр корзины пользователя
    path('add_to_cart/<int:product_id>/', add_to_cart, name='add_to_cart'),
    path('update_cart_item/<int:item_id>/<int:new_count>/', update_cart, name='update_cart_item'),
    path('remove_from_cart/<int:item_id>/', remove_from_cart, name='remove_from_cart'),
    path('cart/', cart_view, name='cart'),

    # Категории
    path('category/<int:category_id>/', category_detail, name='category_detail'),
    path('subcategory/<int:subcategory_id>/', subcategory_detail, name='subcategory_detail'),

    # поиск
    path('search/', search_products, name='search_products'),


]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

accounts/forms.py
# accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserChangeForm
from django.contrib.auth.models import User

class StandardUserCreationForm(forms.ModelForm):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user

class ProfileUpdateForm(UserChangeForm):
    new_password = forms.CharField(label='new_password', widget=forms.PasswordInput(), required=False)

    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name']

    def clean_new_password(self):
        new_password = self.cleaned_data.get('new_password')
        if new_password:
            return new_password
        return None

    def save(self, commit=True):
        user = super().save(commit=False)
        new_password = self.cleaned_data.get('new_password')
        if new_password:
            user.set_password(new_password)
        if commit:
            user.save()
        return user

store/forms.py
from django import forms
from .models import Product

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'description', 'price', 'category', 'subcategory', 'image']

class ProductSearchForm(forms.Form):
    query = forms.CharField(max_length=100, label='Search')

class OrderForm(forms.Form):
    full_name = forms.CharField(max_length=100, label='Full Name')
    address = forms.CharField(max_length=255, label='Address')
    phone_number = forms.CharField(max_length=20, label='Phone Number')


class ContactForm(forms.Form):
    name = forms.CharField(max_length=100, label='Your Name')
    email = forms.EmailField(label='Your Email')
    message = forms.CharField(widget=forms.Textarea, label='Your Message')

accounts/views.py
from django.contrib.auth import login as auth_login, logout as auth_logout, update_session_auth_hash
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from store.models import Cart, CartItem
from .forms import StandardUserCreationForm, ProfileUpdateForm


def signup(request):
    if request.method == 'POST':
        form = StandardUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            messages.success(request, f'Приветствуем вас, {user.username}! Вы успешно зарегистрированы.')
            return redirect('home')
    else:
        form = StandardUserCreationForm()

    return render(request, 'accounts/signup.html', {'form': form})


def log_in_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            user = form.get_user()
            auth_login(request, user)
            messages.success(request, f'С приехалом, {user.username}!')
            return redirect('home')
    else:
        form = AuthenticationForm()

    return render(request, 'accounts/login.html', {'form': form})

@login_required
def log_out_view(request):
    auth_logout(request)
    messages.success(request, 'Вы вышли из магазина.')
    return redirect('home')


@login_required
def profile(request):
    user = request.user

    # Получаем данные о корзине для текущего пользователя
    cart_items = Cart.objects.filter(owner=user)

    if request.method == 'POST':
        form = ProfileUpdateForm(request.POST, instance=user)
        if form.is_valid():
            user = form.save()
            new_password = form.cleaned_data.get('new_password')
            if new_password:
                user.set_password(new_password)
                user.save()
                update_session_auth_hash(request, user)
                messages.success(request, 'Пароль обновлен.')
            else:
                messages.success(request, 'Данные обновлены.')
            return redirect('profile')
        else:
            for field, errors in form.errors.items():
                for error in errors:
                    messages.error(request, f"Ошибка в поле '{form.fields[field].label}': {error}")
    else:
        form = ProfileUpdateForm(instance=user)

    return render(request, 'accounts/profile.html', {'form': form, 'cart_items': cart_items})

@login_required
def profile_view(request):
    user = request.user
    cart, created = Cart.objects.get(owner=user)
    cart_items = cart.cartitem_set.all()
    total_price = sum(item.product.price * item.quantity for item in cart_items)

    context = {
        'user': user,
        'cart_items': cart_items,
        'total_price': total_price,
    }

    return render(request, 'accounts/profile.html', context)

templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}

  {% if messages %}
    <ul class="messages">
      {% for message in messages %}
        {% if message.tags %}
          <li class="{{ message.tags }}">{{ message }}</li>
        {% endif %}
      {% endfor %}
    </ul>
  {% endif %}

  <div class="transparent-container">
    <h3 class="registration-title">Авторизация</h3>
    <form method="post" action="{% url 'login' %}" class="login-form">
      {% csrf_token %}
      <div class="input-container">
        <label for="id_username">Имя пользователя:</label>
        <input type="text" name="username" id="id_username" required>
      </div>

      <div class="input-container">
        <label for="id_password">Пароль:</label>
        <input type="password" name="password" id="id_password" required>
      </div>

      <button type="submit">Войти</button>
    </form>
  </div>
{% endblock %}

templates/accounts/profile.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                {% if message.tags %}
                    <li class="{{ message.tags }}">{{ message }}</li>
                {% endif %}
            {% endfor %}
        </ul>
    {% endif %}

  <div class="transparent-container">
    <h3 class="registration-title">Ваши данные</h3>
    <form method="post" id="profile-form">
      {% csrf_token %}
      <div class="input-container">
        <label for="id_username">Ник Пользователя:</label>
        <input type="text" name="username" id="id_username" value="{{ user.username }}" required>
      </div>

      <div class="input-container">
        <label for="id_first_name">Имя:</label>
        <input type="text" name="first_name" id="id_first_name" value="{{ user.first_name }}" required>
      </div>

      <div class="input-container">
        <label for="id_last_name">Фамилия:</label>
        <input type="text" name="last_name" id="id_last_name" value="{{ user.last_name }}" required>
      </div>

      <div class="input-container">
        <label for="id_email">Email:</label>
        <input type="email" name="email" id="id_email" value="{{ user.email }}" required>
      </div>

      <div class="input-container">
        <label for="id_new_password">Новый пароль:</label>
        <div class="password-container">
          <input type="password" name="new_password" id="id_new_password" placeholder="Введите новый пароль">
          <button type="button" id="show-password" class="show-password-button" style="margin-bottom: 15px;">Показать</button>
        </div>
      </div>

      <div class="input-container">
        <label for="id_confirm_password">Подтвердите пароль:</label>
        <div class="password-con">
          <input type="password" name="confirm_password" id="id_confirm_password" placeholder="Подтвердите пароль" style="width: 100%;">
        </div>
      </div>

      <button type="submit" class="update-profile" style="margin-top: 10px;">Обновить</button>
    </form>
  </div>

<!--    &lt;!&ndash; Вывод товаров в корзине &ndash;&gt;-->
<!--    <div class="cart-items">-->
<!--        <h3>Товары в корзине</h3>-->
<!--        <div class="thumbnails">-->
<!--            {% for item in cart_items %}-->
<!--                <div class="thumbnail">-->
<!--                    <img src="{{ item.product.image.url }}" alt="{{ item.product.name }}">-->
<!--                    <p>{{ item.product.name }}</p>-->
<!--                    <p>Количество: {{ item.quantity }}</p>-->
<!--                </div>-->
<!--            {% endfor %}-->
<!--        </div>-->
<!--        <p>Общая стоимость: {{ total_price }}</p>-->
<!--    </div>-->


  <script>
    document.addEventListener('DOMContentLoaded', function() {
      const passwordInput = document.getElementById('id_new_password');
      const showPasswordButton = document.getElementById('show-password');

      showPasswordButton.addEventListener('click', function() {
        if (passwordInput.type === 'password') {
          passwordInput.type = 'text';
          showPasswordButton.textContent = 'Скрыть';
        } else {
          passwordInput.type = 'password';
          showPasswordButton.textContent = 'Показать';
        }
      });
    });
  </script>
{% endblock %}

templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}
  <div class="transparent-container">
    <h3 class="registration-title">Регистрация</h3>
    <form method="post" action="{% url 'signup' %}">
      {% csrf_token %}
      <div class="input-container">
        <label for="id_username">Ник пользователя:</label>
        <input type="text" name="username" id="id_username" required>
      </div>

      <div class="input-container">
        <label for="id_first_name">Имя:</label>
        <input type="text" name="first_name" id="id_first_name" required>
      </div>

      <div class="input-container">
        <label for="id_last_name">Фамилия:</label>
        <input type="text" name="last_name" id="id_last_name" required>
      </div>

      <div class="input-container">
        <label for="id_email">Email:</label>
        <input type="email" name="email" id="id_email" required>
      </div>

      <div class="input-container">
        <label for="id_password1">Пароль:</label>
        <input type="password" name="password1" id="id_password1" required>
      </div>

      <div class="input-container">
        <label for="id_password2">Повторите пароль:</label>
        <input type="password" name="password2" id="id_password2" required>
      </div>

      <button type="submit" class="done">Готово!</button>
    </form>
  </div>
{% endblock %}