myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from myshop import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('orders/', include('orders.urls')),
    path('', include('store.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)

orders/urls.py
from django.urls import path
from orders import views

urlpatterns = [
    path('checkout/', views.checkout, name='checkout'),
    path('checkout/<int:item_id>/', views.checkout, name='checkout'),
    path('order/<int:order_id>/', views.order_detail, name='order_detail'),
    path('my-orders/', views.my_orders, name='my_orders'),
    path('delete_order/<int:order_id>/', views.delete_order, name='delete_order'),
    path('checkout-all/', views.checkout_all, name='checkout_all'),

]

store/urls.py
# store/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from .views import all_products, category_detail, subcategory_detail, cart_view, add_to_cart, update_cart, remove_from_cart, search_products

urlpatterns = [

    # основные
    path('', views.home, name='home'),
    path('products/', all_products, name='all-products'),
    path('product/<int:product_id>/', views.product_detail, name='product_detail'),

    # Просмотр корзины пользователя
    path('add_to_cart/<int:product_id>/', add_to_cart, name='add_to_cart'),
    path('update_cart_item/<int:item_id>/<int:new_count>/', update_cart, name='update_cart_item'),
    path('remove_from_cart/<int:item_id>/', remove_from_cart, name='remove_from_cart'),
    path('cart/', cart_view, name='cart'),

    # Категории
    path('category/<int:category_id>/', category_detail, name='category_detail'),
    path('subcategory/<int:subcategory_id>/', subcategory_detail, name='subcategory_detail'),

    # поиск
    path('search/', search_products, name='search_products'),


]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/models.py
# -*- coding: utf-8 -*-
from django.contrib.auth.models import User
from django.db import models
from store.models import Product


class Order(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Покупатель")
    date_ordered = models.DateTimeField(auto_now_add=True, verbose_name="Дата оформления")
    total_price = models.DecimalField(max_digits=10, decimal_places=2, default=0.0, verbose_name="Общая стоимость")
    is_ordered = models.BooleanField(default=False, verbose_name="Заказано")
    address = models.CharField(max_length=255, default='', verbose_name="Адрес доставки")
    phone_number = models.CharField(max_length=20, default='', verbose_name="Номер телефона")
    full_name = models.CharField(max_length=100, default='', verbose_name="Полное Имя")
    order_number = models.CharField(max_length=50, default='', verbose_name="Номер заказа")
    user_order_number = models.IntegerField(default=0,  verbose_name="Номер заказа клиента")
    size = models.CharField(max_length=50, default=' ',null=True, blank=True, verbose_name="размер")

    # payment_choices = [(' ', ' '), ('оплата при получении', 'оплата при получении'), ('оплата картой', 'оплата картой')]
    # payment_method = models.CharField(max_length=20, choices=payment_choices, default=' ', verbose_name="способ оплаты")

    STATUS_CHOICES = [
        ('В обработке', 'В обработке'),
        ('В пути', 'В пути'),
        ('Доставлен', 'Доставлен'),
        ('Отменен', 'Отменен'),
    ]
    status = models.CharField(max_length=50, choices=STATUS_CHOICES, default='В обработке', verbose_name="Статус")

    def __str__(self):
        return f"Номер заказа #{self.id} пользователя {self.owner.username}"

    def total_quantity(self):
        return f'{sum(item.quantity for item in self.orderitem_set.all())}'

    def generate_user_order_number(self):
        max_user_order_number = Order.objects.filter(owner=self.owner).aggregate(models.Max('user_order_number'))['user_order_number__max']
        new_user_order_number = max_user_order_number + 1 if max_user_order_number is not None else 1
        return new_user_order_number

    def save(self, *args, **kwargs):
        if not self.id:
            self.user_order_number = self.generate_user_order_number()
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = "Заказ"
        verbose_name_plural = "Оформленные заказы"

class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, verbose_name="Заказ")
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name="Товар")
    quantity = models.PositiveIntegerField(default=1, verbose_name="Количество")
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0.0, verbose_name="Цена")
    description = models.TextField(blank=True, null=True, verbose_name="Описание")

    def __str__(self):
        return f"{self.quantity} {self.product} в заказе #{self.order.id}"

    class Meta:
        verbose_name = 'Элементы заказа'

orders/views.py
# -*- coding: utf-8 -*-
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse

from orders.models import Order
from orders.utils import validate_checkout_data, create_order, create_order_with_items
from store.models import CartItem, Cart


@login_required
def checkout(request, item_id):
    cart_item = get_object_or_404(CartItem, id=item_id)
    total_price = cart_item.product.price * cart_item.quantity

    if request.method == 'POST':
        full_name = request.POST.get('full_name')
        address = request.POST.get('address')
        phone_number = request.POST.get('phone_number')
        size = request.POST.get('size')
        # payment_method = request.POST.get('payment_method')
        username = request.user.username

        validation_result = validate_checkout_data(full_name, username)
        if not validation_result['valid']:
            messages.error(request, validation_result['message'])
            return redirect('checkout', item_id=item_id)

        order = create_order(request.user, total_price, address, phone_number, full_name, cart_item, size)
        messages.success(request, 'Заказ оформлен!')
        return redirect('order_detail', order_id=order.id)

    return render(request, 'orders/checkout.html', {'cart_item': cart_item, 'total_price': total_price})


def checkout_all(request):
    cart = Cart.objects.get(owner=request.user)
    cart_items = CartItem.objects.filter(cart=cart)
    total_price = sum(item.product.price * item.quantity for item in cart_items)

    if request.method == 'POST':
        full_name = request.POST.get('full_name')
        address = request.POST.get('address')
        phone_number = request.POST.get('phone_number')

        username = request.user.username

        validation_result = validate_checkout_data(full_name, username)
        if not validation_result['valid']:
            messages.error(request, validation_result['message'])
            return redirect('checkout_all')

        # Создаем заказ, включающий все товары из корзины
        order = create_order_with_items(request.user, address, phone_number, full_name, cart_items, total_price)

        # Очищаем корзину после оформления заказа
        cart_items.delete()

        messages.success(request, 'Заказ оформлен!')
        # Перенаправляем на страницу деталей заказа
        return redirect(reverse('order_detail', kwargs={'order_id': order.id}))

    return render(request, 'orders/checkout_all.html', {'cart_items': cart_items, 'total_price': total_price})

@login_required
def order_detail(request, order_id):
    order = get_object_or_404(Order, id=order_id, owner=request.user)
    order_items = order.orderitem_set.all()
    return render(request, 'orders/order_detail.html', {'order': order, 'order_items': order_items})

@login_required
def my_orders(request):
    orders = Order.objects.filter(owner=request.user, is_ordered=True).order_by('-date_ordered')
    return render(request, 'orders/my_orders.html', {'orders': orders})

@login_required
def delete_order(request, order_id):
    order = get_object_or_404(Order, id=order_id, owner=request.user)
    order.delete()
    messages.success(request, 'Заказ удален!')
    return HttpResponseRedirect(reverse('my_orders'))

templates/orders/cart.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <h1>Ваша корзина</h1>

  {% if messages %}
    <ul class="messages">
      {% for message in messages %}
        {% if message.tags %}
          <li class="{{ message.tags }}">{{ message }}</li>
        {% endif %}
      {% endfor %}
    </ul>
  {% endif %}

    <div class="cart-body">
        <div class="cart">
            {% if cart_items %}
                {% for item in cart_items %}
                    <div class="product">
                        <a href="{% url 'product_detail' product_id=item.product.id %}">
                            <div class="product-image">
                                <img src="{{ item.product.image.url }}" alt="{{ item.product.name }}">
                            </div>
                        </a>
                        <div class="prodUct-info">
                            <h3>{{ item.product.name }}</h3>
                            <div class="description">{{ item.product.description }}</div>
                            <p><strong>Цена:</strong><span class="price"> {{ item.product.price }}</span> ₽</p>
                        </div>
                        <div class="decr-counter">
                            <a href="{% url 'checkout' item.id %}"><button>Оформить</button></a>
                            <button onclick="decrementCount({{ item.id }})">-</button>
                            <span id="count{{ item.id }}">{{ item.quantity }}</span>
                            <button onclick="incrementCount({{ item.id }})">+</button>
                            <input type="hidden" id="csrf_token" name="csrfmiddlewaretoken" value="{{ csrf_token }}">
                            <button onclick="removeFromCart({{ item.id }})">Удалить</button>
                        </div>
                    </div>
                {% endfor %}
                    <div class="total">Общая стоимость: {{ total_price }} ₽</div>
                {% if cart_items|length > 1 %}
                    <a href="{% url 'checkout_all' %}"><button>Купить все !</button></a>
                {% endif %}
            {% else %}
                <h2>Пуста!</h2>
            {% endif %}
        </div>
    </div>

<script>
            // Перенос строк в описании товара (в корзине)

        var productDescriptions = document.querySelectorAll('.prodUct-info .description');
        productDescriptions.forEach(function(description) {
            var text = description.textContent; // Получаем текст из элемента
            var newText = ''; // Создаем переменную для нового текста
            var charCount = 0; // Счетчик символов

            // Проходимся по каждому символу в тексте
            for (var i = 0; i < text.length; i++) {
                newText += text[i]; // Добавляем символ в новый текст
                charCount++; // Увеличиваем счетчик символов

                // Если счетчик достиг 30 символов, добавляем перенос строки
                if (charCount === 30) {
                    newText += '<br>';
                    charCount = 0; // Сбрасываем счетчик символов
                }
            }

            // Вставляем новый HTML-код с переносами строк внутрь элемента
            description.innerHTML = newText;
        });
</script>

{% endblock %}

templates/orders/checkout.html
{% extends 'base.html' %}

{% block content %}

    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                {% if message.tags %}
                    <li class="{{ message.tags }}">{{ message }}</li>
                {% endif %}
            {% endfor %}
        </ul>
    {% endif %}

  <div class="container">
    <h1>Оформление заказа</h1>
    <div class="row">
      <div class="col-md-6">
        <div class="transparent-container">
          <div class="des"><h3 class="title">Детали доставки</h3></div>
          <form method="post" action="{% url 'checkout' item_id=cart_item.id %}">
            {% csrf_token %}

            <div class="input-container">
              <label for="id_full_name">Ник пользователя</label>
              <input type="text" class="form-control" id="id_full_name" name="full_name" required title="Пожалуйста, введите ваше имя пользователя">
            </div>

            <div class="input-container">
              <label for="id_address">Адрес</label>
              <input type="text" class="form-control" id="id_address" name="address" required placeholder="Город ул. дом\кв">
            </div>

            <div class="input-container">
              <label for="id_phone_number">Номер телефона</label>
              <input type="tel" class="form-control" id="id_phone_number" name="phone_number" required placeholder="номер для связи">
            </div>

            <div class="input-container">
              <label for="id_size">Размер</label>
              <input type="text" class="form-control" id="id_size" name="size" placeholder="Отметьте размер при необходимости">
            </div>

<!--            <div class="des"><h3 class="title">Способ оплаты</h3></div>-->
<!--            <div style="display: flex; justify-content: space-between;">-->
<!--                <label for="payment_cash_on_delivery">Оплата при получении</label>-->
<!--                <input type="radio" id="payment_cash_on_delivery" name="payment_method" value="оплата при получении">-->
<!--                <label for="payment_credit_card">Оплата картой</label>-->
<!--                <input type="radio" id="payment_credit_card" name="payment_method" value="оплата картой">-->
<!--            </div><br>-->

            <button type="submit" class="btn btn-primary">Оформить заказ</button>
          </form>
        </div>
      </div>
      <div class="col-md-6">
        <div class="transparent-container">
          <div class="col-md-4">
            <img src="{{ cart_item.product.image.url }}" class="img-fluid img-small">
          </div>
          <div class="col-md-8">
            <h3>Ваш заказ</h3>
            <strong>{{ cart_item.product.name }}</strong> - ({{ cart_item.quantity }} шт.)
            <p><strong>Общая сумма:</strong> {{ total_price }} руб.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/orders/checkout_all.html
{% extends 'base.html' %}

{% block content %}

    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                {% if message.tags %}
                    <li class="{{ message.tags }}">{{ message }}</li>
                {% endif %}
            {% endfor %}
        </ul>
    {% endif %}

  <div class="container">
    <h2>Оформление заказа</h2>
    <div class="row">
      <div class="col-md-6">
        <div class="transparent-container">
          <div class="des"><h3 class="title">Детали доставки</h3></div>
          <form method="post" action="{% url 'checkout_all' %}">
            {% csrf_token %}

            <div class="input-container">
              <label for="id_full_name">Ник пользователя</label>
              <input type="text" class="form-control" id="id_full_name" name="full_name" title="Пожалуйста, введите ваше имя пользователя">
            </div>

            <div class="input-container">
              <label for="id_address">Адрес</label>
              <input type="text" class="form-control" id="id_address" name="address" placeholder="Город ул. дом\кв">
            </div>

            <div class="input-container">
              <label for="id_phone_number">Номер телефона</label>
              <input type="tel" class="form-control" id="id_phone_number" name="phone_number" required placeholder="номер для связи">
            </div>

            <div class="input-container">
              <label for="id_size">Размер</label>
              <input type="text" class="form-control" id="id_size" name="size" placeholder="Отметьте размеры моделей">
            </div>

            <button type="submit" class="btn btn-primary">Оформить все заказы</button>
          </form>
        </div>
      </div>
      <div class="col-md-6">
        <div class="transparent-container">
          <h3>Ваши заказы</h3>
          <ul class="list-group">
            {% for cart_item in cart_items %}
              <div class="row">
                <div class="col-md-4">
                  <img src="{{ cart_item.product.image.url }}" class="img-fluid img-small">
                </div>
                <div class="col-md-8">
                  <p>{{ cart_item.product.name }} ({{ cart_item.quantity }} шт.)</p>
                  {% with total_price=cart_item.product.price|add:"0"|add:cart_item.quantity %}
                  {% endwith %}
                </div>
              </div>
            {% endfor %}
          </ul>
          <p>Общая сумма всех заказов: {{ total_price }} руб.</p>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/orders/my_orders.html
{% extends 'base.html' %}

{% block content %}

    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                {% if message.tags %}
                    <li class="{{ message.tags }}">{{ message }}</li>
                {% endif %}
            {% endfor %}
        </ul>
    {% endif %}

  <h1>Мои заказы</h1>
  <div class="order-list">
    {% if orders %}
      {% for order in orders %}
        <div class="cart">
          <div class="order-1">
            <a href="{% url 'order_detail' order_id=order.id %}" class="order-link">
              <span class="order-number">Посмотреть заказ № {{ order.order_number }}</span>
            </a>
          </div>
          <div class="order-info">
            <p><strong>Адрес доставки:</strong> {{ order.address }}</p>
            <p><strong>Номер телефона:</strong> {{ order.phone_number }}</p>
            <p><strong>Количество товаров в заказе:</strong> {{ order.orderitem_set.count }}</p>
            <p><strong>Сумма заказа:</strong> {{ order.total_price }} ₽</p>
          </div>
          <form action="{% url 'delete_order' order_id=order.id %}" method="post">
            {% csrf_token %}
            <button type="submit">Удалить</button>
          </form>
        </div>
      {% endfor %}
    {% else %}
      <p>У вас пока нет заказов.</p>
    {% endif %}
  </div>
{% endblock %}

templates/orders/order_detail.html
{% extends 'base.html' %}

{% block content %}

    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                {% if message.tags %}
                    <li class="{{ message.tags }}">{{ message }}</li>
                {% endif %}
            {% endfor %}
        </ul>
    {% endif %}

  <div class="container">
    <h2>Детали заказа №{{ order.order_number }}</h2>
    <p>Дата заказа: {{ order.date_ordered }}</p>
    <div class="row">
      {% for order_item in order_items %}
        <div class="col-md-4">
          {% if order_item.product.image %}
              <a href="{% url 'product_detail' product_id=order_item.product.id %}">
                  <img src="{{ order_item.product.image.url }}" alt="{{ order_item.product.name }}" class="img-fluid img-small">
              </a>
          {% endif %}
        </div>
        <div class="col-md-8">
          <p><strong>{{ order_item.product.name }}</strong></p>
            <p><strong>Статус заказа:</strong> {{ order.status }}</p> <!-- Добавьте статус заказа -->
          <p><strong>Количество:</strong> {{ order_item.quantity }} шт.</p>
          <p>{{ order_item.description }}</p>
        </div>
      {% endfor %}
    </div>
    <p><strong>Общая сумма заказа:</strong> {{ order.total_price }} руб.</p>
    <p><strong>Адрес доставки:</strong> {{ order.address }}</p> <!-- Добавьте адрес доставки -->
    <p><strong>Номер телефона:</strong> {{ order.phone_number }}</p> <!-- Добавьте номер телефона -->
    <!-- Здесь можно добавить другие детали заказа, если необходимо -->
  </div>
{% endblock %}